services:
  db:
    image: pgvector/pgvector:0.8.0-pg17
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
